name: EVSSM_LR_Finder
model_type: ImageRestorationModel
scale: 1
num_gpu: 1
manual_seed: 42
find_lr: true  # Enable LR finder mode

datasets:
  train:
    name: gopro-train
    type: PairedImageDataset
    dataroot_gt: datasets/GoPro/train/sharp_crops.lmdb
    dataroot_lq: datasets/GoPro/train/blur_crops.lmdb

    filename_tmpl: '{}'
    io_backend:
      type: lmdb

    gt_size: 128
    use_flip: false  # Disable augmentation for LR finding
    use_rot: false

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 2
    batch_size_per_gpu: 4 # Keep same as training
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

network_g:
  type: EVSSM
  inp_channels: 3
  out_channels: 3
  dim: 48
  num_blocks: [6,6,12]
  ffn_expansion_factor: 3
  bias: False

# path
path:
  pretrain_network_g:
  strict_load_g:
  resume_state:

# training settings
train:
  optim_g:
    type: AdamW
    lr: !!float 1e-7  # Starting LR (will be overridden)
    weight_decay: !!float 1e-3
    betas: [0.9, 0.9]

  scheduler:
    type: TrueCosineAnnealingLR
    T_max: 300000
    eta_min: !!float 1e-7

  total_iter: 500  # Not used in LR finder
  warmup_iter: 0

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

  fft_loss_opt:
    type: FFTLoss
    loss_weight: 0.1
    reduction: mean

# logging settings
logger:
  print_freq: 10
  save_checkpoint_freq: !!float 1e10  # Don't save during LR finding
  use_tb_logger: false
  wandb:
    project: ~
    resume_id: ~